[flake8]
max-line-length = 120
max-complexity = 10

[isort]
multi_line_output = 3
include_trailing_comma = true
default_section = THIRDPARTY
line_length = 120
length_sort = 1
known_first_party = blocks, tests

[mypy]
# Untyped definitions and calls:
#   https://mypy.readthedocs.io/en/stable/config_file.html#untyped-definitions-and-calls
python_version = 3.9
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True

# Configuring warnings
#   https://mypy.readthedocs.io/en/stable/config_file.html#configuring-warnings
warn_redundant_casts = True
warn_unused_ignores = True

no_implicit_optional = True
strict_optional = True
exclude = docs|setup.py

[pydantic-mypy]
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True
warn_untyped_fields = True